#!/usr/bin/env python3
import os
import re
import sys

def remove_emojis(text):
    # Unicode ranges for emojis
    emoji_pattern = re.compile(
        r'[\U0001F600-\U0001F64F'  # Emoticons
        r'\U0001F300-\U0001F5FF'  # Misc Symbols and Pictographs
        r'\U0001F680-\U0001F6FF'  # Transport and Map
        r'\U0001F1E0-\U0001F1FF'  # Regional Indicator Symbols
        r'\U00002600-\U000026FF'  # Misc symbols
        r'\U00002700-\U000027BF'  # Dingbats
        r'\U0001F900-\U0001F9FF'  # Supplemental Symbols and Pictographs
        r']+',
        flags=re.UNICODE
    )
    return emoji_pattern.sub('', text)

def process_file(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        cleaned = remove_emojis(content)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(cleaned)
        print(f"Processed: {filepath}")
    except Exception as e:
        print(f"Error processing {filepath}: {e}")

if __name__ == "__main__":
    files_to_process = [
        "./mcp-servers/images/kubernetes-mcp-server-image.tar",
        "./mcp-servers/images/prometheus-mcp-server.tar",
        "./mcp-servers/images/esxi-mcp-server.tar",
        "./mcp-servers/images/grafana-mcp-server.tar",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/pygments/filters/__pycache__/__init__.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/pygments/__pycache__/unistring.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/requests/status_codes.py",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/requests/__pycache__/__version__.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/requests/__pycache__/status_codes.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/_spinners.py",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/tree.py",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/syntax.py",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/_emoji_codes.py",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/__main__.py",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/cells.py",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/control.py",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/_spinners.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/control.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/cells.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/__main__.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/syntax.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/tree.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/_emoji_codes.cpython-312.pyc",
        "./mcp-servers/images/test_venv/lib/python3.12/site-packages/httpx-0.28.1.dist-info/METADATA",
        "./mcp-servers/prometheus-mcp-server/direct_test_prometheus.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/uvicorn-0.38.0.dist-info/METADATA",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pkg_resources/tests/test_pkg_resources.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pkg_resources/tests/__pycache__/test_pkg_resources.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/setuptools/tests/__pycache__/test_bdist_wheel.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/fastapi-0.124.4.dist-info/METADATA",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/annotated_types/test_cases.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/annotated_types/__pycache__/test_cases.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/pygments/filters/__pycache__/__init__.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/pygments/__pycache__/unistring.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/requests/status_codes.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/requests/__pycache__/__version__.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/requests/__pycache__/status_codes.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/_spinners.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/tree.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/syntax.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/_emoji_codes.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/__main__.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/cells.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/control.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/_spinners.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/control.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/cells.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/__main__.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/syntax.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/tree.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/_emoji_codes.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/charset_normalizer-3.4.4.dist-info/METADATA",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/pydantic_core-2.41.5.dist-info/METADATA",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/uvloop/loop.cpython-312-x86_64-linux-gnu.so",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/charset_normalizer/md__mypyc.cpython-312-x86_64-linux-gnu.so",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/requests/status_codes.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/requests/__pycache__/__version__.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/requests/__pycache__/status_codes.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/fastapi/applications.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/fastapi/__pycache__/applications.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/starlette-0.50.0.dist-info/METADATA",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/regex/tests/__pycache__/test_regex.cpython-312.pyc",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/urllib3-2.6.2.dist-info/METADATA",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/dateutil/zoneinfo/dateutil-zoneinfo.tar.gz",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/watchfiles/cli.py",
        "./mcp-servers/prometheus-mcp-server/.venv/lib/python3.12/site-packages/watchfiles/__pycache__/cli.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/test_api/delete_vm_test.py",
        "./mcp-servers/esxi-mcp-server/test_api/create_vm_test.py",
        "./mcp-servers/esxi-mcp-server/test_api/comprehensive_test.py",
        "./mcp-servers/esxi-mcp-server/test_api/vm_performance_test.py",
        "./mcp-servers/esxi-mcp-server/Makefile",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/uvicorn-0.38.0.dist-info/METADATA",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/filters/__pycache__/__init__.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/lexers/mojo.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/lexers/bqn.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/lexers/_mapping.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/lexers/__pycache__/_mapping.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/lexers/__pycache__/mojo.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/lexers/__pycache__/bqn.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/lexers/__pycache__/perl.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pygments/__pycache__/unistring.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/cryptography/hazmat/bindings/_rust.abi3.so",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/annotated_types/test_cases.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/annotated_types/__pycache__/test_cases.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/pygments/filters/__pycache__/__init__.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/pygments/__pycache__/unistring.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/requests/status_codes.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/requests/__pycache__/__version__.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/requests/__pycache__/status_codes.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/_spinners.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/tree.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/syntax.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/_emoji_codes.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/__main__.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/cells.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/control.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/_spinners.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/control.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/cells.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/__main__.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/syntax.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/tree.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/_emoji_codes.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/charset_normalizer-3.4.4.dist-info/METADATA",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/httpx-0.28.1.dist-info/METADATA",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/pydantic_core-2.41.5.dist-info/METADATA",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/urllib3-2.5.0.dist-info/METADATA",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/mcp/server/fastmcp/utilities/func_metadata.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/charset_normalizer/md__mypyc.cpython-312-x86_64-linux-gnu.so",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/requests/status_codes.py",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/requests/__pycache__/__version__.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/requests/__pycache__/status_codes.cpython-312.pyc",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/starlette-0.50.0.dist-info/METADATA",
        "./mcp-servers/esxi-mcp-server/venv/lib/python3.12/site-packages/_pytest/config/argparsing.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/pygments/filters/__pycache__/__init__.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/pygments/__pycache__/unistring.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/requests/status_codes.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/requests/__pycache__/__version__.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/requests/__pycache__/status_codes.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/_spinners.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/tree.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/syntax.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/_emoji_codes.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/__main__.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/cells.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/control.py",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/_spinners.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/control.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/cells.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/__main__.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/syntax.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/tree.cpython-312.pyc",
        "./mcp-servers/temp_venv/lib/python3.12/site-packages/pip/_vendor/rich/__pycache__/_emoji_codes.cpython-312.pyc",
        "./mcp-servers/mcp-server-kubernetes/scripts/update-version.js",
        "./mcp-servers/mcp-server-kubernetes/bun.lockb",
        "./mcp-servers/mcp-server-kubernetes/README.md",
        "./mcp-servers/mcp-server-kubernetes/test-connectivity.sh",
        "./mcp-servers/mcp-server-kubernetes/test-http-connectivity.sh",
        "./mcp-servers/mcp-server-kubernetes/icon.png",
        "./mcp-servers/mcp-server-kubernetes/ADVANCED_README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/raw-body/node_modules/iconv-lite/Changelog.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/raw-body/node_modules/iconv-lite/encodings/internal.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/raw-body/node_modules/iconv-lite/encodings/tables/cp949.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/raw-body/node_modules/iconv-lite/encodings/tables/eucjp.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/raw-body/node_modules/iconv-lite/encodings/tables/big5-added.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/raw-body/node_modules/iconv-lite/encodings/tables/cp950.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/raw-body/node_modules/iconv-lite/encodings/tables/shiftjis.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/raw-body/node_modules/iconv-lite/encodings/tables/cp936.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/jose/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/yoctocolors-cjs/readme.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/resolve/.github/THREAT_MODEL.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/pathe/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/emoji-regex/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/openid-client/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/punycode/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/bare-url/prebuilds/win32-arm64/bare-url.bare",
        "./mcp-servers/mcp-server-kubernetes/node_modules/bare-url/prebuilds/win32-x64/bare-url.bare",
        "./mcp-servers/mcp-server-kubernetes/node_modules/fflate/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/qs/test/parse.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/qs/test/stringify.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/qs/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/qs/lib/parse.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/qs/lib/stringify.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/dist/cjs/examples/server/demoInMemoryOAuthProvider.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/dist/cjs/examples/server/demoInMemoryOAuthProvider.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/dist/cjs/examples/client/simpleStreamableHttp.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/dist/cjs/examples/client/simpleOAuthClient.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/dist/esm/examples/server/demoInMemoryOAuthProvider.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/dist/esm/examples/server/demoInMemoryOAuthProvider.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/dist/esm/examples/client/simpleStreamableHttp.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/dist/esm/examples/client/simpleOAuthClient.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/cjs/node_modules/zod/v4/core/errors.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/cjs/node_modules/zod/v4/core/errors.d.cts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/cjs/node_modules/zod/v4/core/errors.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/cjs/node_modules/zod/v4/core/errors.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/types/node_modules/zod/v4/core/errors.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/types/node_modules/zod/v4/core/errors.d.cts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/types/node_modules/zod/v4/core/errors.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/types/node_modules/zod/v4/core/errors.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/esm/node_modules/zod/v4/core/errors.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/esm/node_modules/zod/v4/core/errors.d.cts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/esm/node_modules/zod/v4/core/errors.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v4/esm/node_modules/zod/v4/core/errors.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/cjs/node_modules/zod/v4/core/errors.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/cjs/node_modules/zod/v4/core/errors.d.cts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/cjs/node_modules/zod/v4/core/errors.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/cjs/node_modules/zod/v4/core/errors.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/types/node_modules/zod/v4/core/errors.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/types/node_modules/zod/v4/core/errors.d.cts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/types/node_modules/zod/v4/core/errors.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/types/node_modules/zod/v4/core/errors.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/esm/node_modules/zod/v4/core/errors.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/esm/node_modules/zod/v4/core/errors.d.cts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/esm/node_modules/zod/v4/core/errors.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod-to-json-schema/dist-test-v3/esm/node_modules/zod/v4/core/errors.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/body-parser/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/qs/test/parse.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/qs/test/stringify.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/qs/test/utils.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/qs/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/qs/lib/parse.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/qs/lib/stringify.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/src/v3/tests/refine.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/src/v3/tests/string.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/src/v4/mini/tests/string.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/src/v4/classic/tests/refine.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/src/v4/classic/tests/string.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/src/v4/classic/tests/error-utils.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/src/v4/core/errors.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/v4/core/errors.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/v4/core/errors.d.cts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/v4/core/errors.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/zod/v4/core/errors.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/iconv-lite/Changelog.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/iconv-lite/encodings/internal.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/iconv-lite/encodings/tables/cp949.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/iconv-lite/encodings/tables/eucjp.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/iconv-lite/encodings/tables/big5-added.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/iconv-lite/encodings/tables/cp950.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/iconv-lite/encodings/tables/shiftjis.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@modelcontextprotocol/sdk/node_modules/iconv-lite/encodings/tables/cp936.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/text-decoder/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/type-fest/readme.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/vitest/dist/chunks/index.BJDntFik.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/vitest/dist/chunks/reporters.nr4dxCkA.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@types/node/punycode.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/magic-string/dist/magic-string.es.mjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/magic-string/dist/magic-string.cjs.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/magic-string/dist/magic-string.cjs.js.map",
        "./mcp-servers/mcp-server-kubernetes/node_modules/magic-string/dist/magic-string.umd.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/magic-string/dist/magic-string.umd.js.map",
        "./mcp-servers/mcp-server-kubernetes/node_modules/magic-string/dist/magic-string.es.mjs.map",
        "./mcp-servers/mcp-server-kubernetes/node_modules/stream-buffers/.github/workflows/codeql-analysis.yml",
        "./mcp-servers/mcp-server-kubernetes/node_modules/eventsource/src/errors.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/eventsource/dist/index.js.map",
        "./mcp-servers/mcp-server-kubernetes/node_modules/eventsource/dist/index.cjs.map",
        "./mcp-servers/mcp-server-kubernetes/node_modules/eventsource-parser/src/parse.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/eventsource-parser/dist/index.js.map",
        "./mcp-servers/mcp-server-kubernetes/node_modules/eventsource-parser/dist/index.cjs.map",
        "./mcp-servers/mcp-server-kubernetes/node_modules/esbuild/bin/esbuild",
        "./mcp-servers/mcp-server-kubernetes/node_modules/vite/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/vite/dist/node-cjs/publicUtils.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/vite/dist/node/chunks/dep-BK3b2jBa.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/expect-type/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/expect-type/dist/messages.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/expect-type/dist/index.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@inquirer/prompts/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@inquirer/core/dist/cjs/types/lib/theme.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@inquirer/core/dist/esm/types/lib/theme.d.mts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@inquirer/figures/dist/commonjs/index.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@inquirer/figures/dist/esm/index.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/zod/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/iconv-lite/encodings/internal.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/iconv-lite/encodings/tables/cp949.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/iconv-lite/encodings/tables/eucjp.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/iconv-lite/encodings/tables/big5-added.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/iconv-lite/encodings/tables/cp950.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/iconv-lite/encodings/tables/shiftjis.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/iconv-lite/encodings/tables/cp936.json",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@esbuild/linux-x64/bin/esbuild",
        "./mcp-servers/mcp-server-kubernetes/node_modules/oauth4webapi/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/rollup/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/rollup/dist/shared/rollup.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/rollup/dist/es/shared/node-entry.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/tinyexec/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/tinypool/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/tinyspy/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/dist/cli/pack.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/src/v3/tests/refine.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/src/v3/tests/string.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/src/v4/mini/tests/string.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/src/v4/classic/tests/refine.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/src/v4/classic/tests/string.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/src/v4/classic/tests/error-utils.test.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/src/v4/core/errors.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/v4/core/errors.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/v4/core/errors.d.cts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/v4/core/errors.js",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@anthropic-ai/mcpb/node_modules/zod/v4/core/errors.cjs",
        "./mcp-servers/mcp-server-kubernetes/node_modules/shx/CHANGELOG.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@kubernetes/client-node/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/@kubernetes/client-node/node_modules/@types/node/punycode.d.ts",
        "./mcp-servers/mcp-server-kubernetes/node_modules/socks/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/cac/README.md",
        "./mcp-servers/mcp-server-kubernetes/node_modules/tinybench/README.md",
        "./mcp-servers/mcp-server-kubernetes/helm-chart/values.yaml",
        "./mcp-servers/mcp-server-kubernetes/helm-chart/templates/tests/test-mcp-tools.yaml",
        "./mcp-servers/mcp-server-kubernetes/helm-chart/templates/tests/test-connectivity.yaml",
        "./mcp-servers/mcp-server-kubernetes/helm-chart/templates/tests/test-scripts-configmap.yaml",
        "./mcp-servers/mcp-server-kubernetes/helm-chart/templates/tests/test-kubeconfig.yaml",
        "./mcp-servers/mcp-server-kubernetes/helm-chart/templates/configmap.yaml",
        "./mcp-servers/mcp-server-kubernetes/helm-chart/README.md",
        "./mcp-servers/__pycache__/test_grafana_mcp_client.cpython-312.pyc",
        "./frontend/db/custom.db",
    ]

    for filepath in files_to_process:
        if os.path.exists(filepath):
            process_file(filepath)
        else:
            print(f"File not found: {filepath}")

    print("Emoji removal completed.")
