-- AlterTable
ALTER TABLE "UserSettings" ADD COLUMN "chunkOverlap" INTEGER DEFAULT 50;
ALTER TABLE "UserSettings" ADD COLUMN "chunkSize" INTEGER DEFAULT 512;
ALTER TABLE "UserSettings" ADD COLUMN "defaultCollection" TEXT DEFAULT 'documents';
ALTER TABLE "UserSettings" ADD COLUMN "documentFolderPath" TEXT DEFAULT './documents';
ALTER TABLE "UserSettings" ADD COLUMN "embedModelName" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "embeddingModel" TEXT DEFAULT 'all-MiniLM-L6-v2';
ALTER TABLE "UserSettings" ADD COLUMN "infrastructureKeywords" TEXT DEFAULT 'docker,kubernetes,k8s,server,database,db,port,host,endpoint,api,aws,azure,gcp,cloud,infra,infrastructure,deploy,container,cluster,virtual machine,vm,network,load balancer,storage,backup,monitoring,logging,alert,scaling,auto-scal,firewall,security,ssl,certificate,domain,subdomain';
ALTER TABLE "UserSettings" ADD COLUMN "langfuseEnabled" BOOLEAN DEFAULT true;
ALTER TABLE "UserSettings" ADD COLUMN "langfuseHost" TEXT DEFAULT 'http://localhost:3001';
ALTER TABLE "UserSettings" ADD COLUMN "langfusePublicKey" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "langfuseSampleRate" REAL DEFAULT 1.0;
ALTER TABLE "UserSettings" ADD COLUMN "langfuseSecretKey" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "llmModel" TEXT DEFAULT 'microsoft/DialoGPT-medium';
ALTER TABLE "UserSettings" ADD COLUMN "llmTemperature" REAL DEFAULT 0.7;
ALTER TABLE "UserSettings" ADD COLUMN "logLevel" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "lokiUrl" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "maxNewTokens" INTEGER;
ALTER TABLE "UserSettings" ADD COLUMN "maxUploadSize" INTEGER DEFAULT 10485760;
ALTER TABLE "UserSettings" ADD COLUMN "networkCidr" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "postgresUrl" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "prometheusUrl" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "qdrantApiKey" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "qdrantUrl" TEXT DEFAULT 'http://localhost:6333';
ALTER TABLE "UserSettings" ADD COLUMN "qdrantUseCloud" BOOLEAN DEFAULT false;
ALTER TABLE "UserSettings" ADD COLUMN "queueDir" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "redisUrl" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "scanCron" TEXT;
ALTER TABLE "UserSettings" ADD COLUMN "topKRetrieval" INTEGER;
ALTER TABLE "UserSettings" ADD COLUMN "useRedisQueue" BOOLEAN DEFAULT false;
